<div id="header">
    <p style="color:black; text-align:center; font-weight:bold; font-family:Tahoma, sans-serif; font-size:24px;">
        Data Gathering with CSV
    </p>
</div>

<div style="background-color:#bfbfbf; padding:8px; border:2px dotted black; border-radius:8px; font-family:sans-serif; line-height: 1.7em">

Data gathering is the first and one of the most essential steps in the machine learning workflow.

**CSV (Comma-Separated Values)** files are a popular format for data storage and exchange due to their simplicity and compatibility with various data processing tools. They store data in a structured, table-like format, where each row corresponds to a record and each column to a field. Their lightweight nature and ease of use make them an ideal choice for machine learning projects.

**Key points about CSV files:**
- CSV files are human-readable and store data in plain text.
- They are widely compatible with tools like Python’s pandas for easy data manipulation and analysis.
- The simplicity of CSV files makes them a great option for exchanging data across different platforms.


</div>

In [68]:
#import statements
import pandas as pd

In [69]:
# Load dataset
df = pd.read_csv('adult_census_income.csv')

In [70]:
df.head()

,age,workclass,education,marital.status,occupation,sex,native.country,income
0,90,?,HS-grad,Widowed,?,Female,United-States,<=50K
1,82,Private,HS-grad,Widowed,Exec-managerial,Female,United-States,<=50K
2,66,?,Some-college,Widowed,?,Female,United-States,<=50K
3,54,Private,7th-8th,Divorced,Machine-op-inspct,Female,United-States,<=50K
4,41,Private,Some-college,Separated,Prof-specialty,Female,United-States,<=50K

# **Read TSV file**

In [71]:
#tsv file
pd.read_csv('titles.tsv',sep='\t',names=['sno','name','year','rate','votes','genres']) #the first row has become as column name

,sno,name,year,rate,votes,genres
0,m0,10 things i hate about you,1999,6.9,62847.0,['comedy' 'romance']
1,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
2,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
3,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
4,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
...,...,...,...,...,...,...
612,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
613,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
614,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
615,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
616,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

# **Use Particular Columns**

In [72]:
#Use only columns
pd.read_csv('adult_census_income.csv',usecols=['education','occupation','income'])

          education         occupation income
0           HS-grad                  ?  <=50K
1           HS-grad    Exec-managerial  <=50K
2      Some-college                  ?  <=50K
3           7th-8th  Machine-op-inspct  <=50K
4      Some-college     Prof-specialty  <=50K
...             ...                ...    ...
32556  Some-college    Protective-serv  <=50K
32557    Assoc-acdm       Tech-support  <=50K
32558       HS-grad  Machine-op-inspct   >50K
32559       HS-grad       Adm-clerical  <=50K
32560       HS-grad       Adm-clerical  <=50K

[32561 rows x 3 columns]

# **Skip Rows**

In [73]:
#skip rows
pd.read_csv('adult_census_income.csv',skiprows=[1,3])

,age,workclass,education,marital.status,occupation,sex,native.country,income
0,82,Private,HS-grad,Widowed,Exec-managerial,Female,United-States,<=50K
1,54,Private,7th-8th,Divorced,Machine-op-inspct,Female,United-States,<=50K
2,41,Private,Some-college,Separated,Prof-specialty,Female,United-States,<=50K
3,34,Private,HS-grad,Divorced,Other-service,Female,United-States,<=50K
4,38,Private,10th,Separated,Adm-clerical,Male,United-States,<=50K
...,...,...,...,...,...,...,...,...
32554,22,Private,Some-college,Never-married,Protective-serv,Male,United-States,<=50K
32555,27,Private,Assoc-acdm,Married-civ-spouse,Tech-support,Female,United-States,<=50K
32556,40,Private,HS-grad,Married-civ-spouse,Machine-op-inspct,Male,United-States,>50K
32557,58,Private,HS-grad,Widowed,Adm-clerical,Female,United-States,<=50K
32558,22,Private,HS-grad,Never-married,Adm-clerical,Male,United-States,<=50K

In [74]:
#skip n rows
pd.read_csv('adult_census_income.csv',nrows=100)

,age,workclass,education,marital.status,occupation,sex,native.country,income
0,90,?,HS-grad,Widowed,?,Female,United-States,<=50K
1,82,Private,HS-grad,Widowed,Exec-managerial,Female,United-States,<=50K
2,66,?,Some-college,Widowed,?,Female,United-States,<=50K
3,54,Private,7th-8th,Divorced,Machine-op-inspct,Female,United-States,<=50K
4,41,Private,Some-college,Separated,Prof-specialty,Female,United-States,<=50K
...,...,...,...,...,...,...,...,...
95,46,Private,Bachelors,Married-civ-spouse,Adm-clerical,Male,Philippines,>50K
96,46,Self-emp-not-inc,Prof-school,Married-civ-spouse,Prof-specialty,Male,United-States,>50K
97,39,Self-emp-inc,Assoc-voc,Married-civ-spouse,Craft-repair,Male,United-States,>50K
98,39,Private,Prof-school,Married-civ-spouse,Sales,Male,United-States,>50K
99,55,Private,Doctorate,Married-civ-spouse,Prof-specialty,Male,United-States,>50K

# **Encoding Parameter and Skip Bad Lines**

CSV files can be encoded in various formats, and sometimes the default encoding (UTF-8) might not work for certain files.

In [75]:
pd.read_csv('zomato.csv', encoding='latin-1', on_bad_lines='skip')   #This will skip the lines that are causing the issue.

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,NamlÛ± Gurme,208,ÛÁstanbul,"Kemankeô Karamustafa Paôa Mahallesi, RÛ±htÛ±...",Karakí_y,"Karakí_y, ÛÁstanbul",28.977392,41.022793,Turkish,...,Turkish Lira(TL),No,No,No,No,3,4.1,Green,Very Good,788
9547,5908749,Ceviz AÛôacÛ±,208,ÛÁstanbul,"Koôuyolu Mahallesi, Muhittin íìstí_ndaÛô Cadd...",Koôuyolu,"Koôuyolu, ÛÁstanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,1034
9548,5915807,Huqqa,208,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.034640,41.055817,"Italian, World Cuisine",...,Turkish Lira(TL),No,No,No,No,4,3.7,Yellow,Good,661
9549,5916112,Aôôk Kahve,208,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.036019,41.057979,Restaurant Cafe,...,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,ÛÁstanbul,"CafeaÛôa Mahallesi, BademaltÛ± Sokak, No 21/B,...",Moda,"Moda, ÛÁstanbul",29.026016,40.984776,Cafe,...,Turkish Lira(TL),No,No,No,No,2,4.0,Green,Very Good,591

# **dtypes parameter**

The dtype parameter specifies the data type that you want to apply to certain columns when reading the CSV file.

In [77]:
pd.read_csv('adult_census_income.csv',dtype={'age':int}).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   education       32561 non-null  object
 3   marital.status  32561 non-null  object
 4   occupation      32561 non-null  object
 5   sex             32561 non-null  object
 6   native.country  32561 non-null  object
 7   income          32561 non-null  object
dtypes: int64(1), object(7)
memory usage: 2.0+ MB

# **Handling Dates**

In [78]:
pd.read_csv('IPL_Dates.csv',parse_dates=['date']).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    object
 2   date             816 non-null    datetime64[ns]
 3   player_of_match  812 non-null    object
 4   venue            816 non-null    object
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    object
 7   team2            816 non-null    object
 8   toss_winner      816 non-null    object
 9   toss_decision    816 non-null    object
 10  winner           812 non-null    object
 11  result           812 non-null    object
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    object
 14  method           19 non-null     object
 15  umpire1          816 non-null    object
 16  umpire2          816 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(2), object(13)
memory usage: 108.5+ KB

<ipython-input-78-a35f1aee8b26>:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  pd.read_csv('IPL_Dates.csv',parse_dates=['date']).info()

# **Converters**

The converters parameter in pd.read_csv() is used to apply custom functions to specific columns while reading a CSV file. This allows you to transform or process the data in a particular column as it's being loaded into a Pandas DataFrame.

In [79]:
def rename(name):
    if name == "Mumbai Indians":
        return "MI"
    else:
        return name

rename("Mumbai Indians")

'MI'

In [80]:
pd.read_csv('IPL_Dates.csv',converters={'team1':rename})

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,18/04/2008,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,19/04/2008,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,19/04/2008,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,20/04/2008,MV Boucher,Wankhede Stadium,0,MI,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,20/04/2008,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,28/09/2020,AB de Villiers,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
812,1237177,Dubai,05/11/2020,JJ Bumrah,Dubai International Cricket Stadium,0,MI,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
813,1237178,Abu Dhabi,06/11/2020,KS Williamson,Sheikh Zayed Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi
814,1237180,Abu Dhabi,08/11/2020,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi
815,1237181,Dubai,10/11/2020,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon

# **Loading huge dataset**

The chunksize parameter in pd.read_csv() is used to read large CSV files in smaller, more manageable chunks rather than loading the entire file into memory at once.

In [81]:
dfs = pd.read_csv('adult_census_income.csv',chunksize=8000)

In [82]:
for chunks in dfs:
    print(chunks.shape)

(8000, 8)
(8000, 8)
(8000, 8)
(8000, 8)
(561, 8)